-- Complete Database DDL for d105 and d105_read schemas
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

-- Create d105 schema
CREATE SCHEMA IF NOT EXISTS d105;

-- Create d105_read schema
CREATE SCHEMA IF NOT EXISTS d105_read;

-- ==============================================
-- D105 SCHEMA - Original Tables
-- ==============================================

CREATE TABLE IF NOT EXISTS d105.account_transactions
(
    transaction_id bigint NOT NULL,
    account_id bigint NOT NULL,
    account_transaction_type character varying(30) COLLATE pg_catalog."default" NOT NULL,
    balance_after integer NOT NULL,
    category_id smallint NOT NULL DEFAULT 1,
    CONSTRAINT account_transactions_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS d105.card_transactions
(
    transaction_id bigint NOT NULL,
    card_id bigint NOT NULL,
    merchant_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    category_id smallint NOT NULL,
    CONSTRAINT card_transactions_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS d105.categories
(
    category_id smallint NOT NULL,
    category_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS d105.group_members
(
    member_id bigserial NOT NULL,
    group_id bigint NOT NULL,
    user_id bigint NOT NULL,
    display_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    member_status smallint NOT NULL,
    allowed_at character varying(30) COLLATE pg_catalog."default",
    rejected_at character varying(30) COLLATE pg_catalog."default",
    exited_at character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT group_members_pkey PRIMARY KEY (member_id)
);

CREATE TABLE IF NOT EXISTS d105.group_tracking_cards
(
    tracking_id bigint NOT NULL,
    member_id bigint NOT NULL,
    card_id bigint NOT NULL,
    is_connected boolean NOT NULL DEFAULT true,
    CONSTRAINT group_tracking_cards_pkey PRIMARY KEY (tracking_id),
    CONSTRAINT group_tracking_cards_member_id_card_id_key UNIQUE (member_id, card_id)
);

CREATE TABLE IF NOT EXISTS d105.groups
(
    group_id bigserial NOT NULL,
    owner_id bigint NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(100) COLLATE pg_catalog."default",
    invitation_code character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    savings_account_no character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT groups_pkey PRIMARY KEY (group_id),
    CONSTRAINT groups_invitation_code_key UNIQUE (invitation_code)
);

CREATE TABLE IF NOT EXISTS d105.member_tracking_accounts
(
    tracking_id bigint NOT NULL,
    member_id bigint NOT NULL,
    account_id bigint NOT NULL,
    is_connected boolean NOT NULL DEFAULT true,
    CONSTRAINT member_tracking_accounts_pkey PRIMARY KEY (tracking_id),
    CONSTRAINT member_tracking_accounts_member_id_account_id_key UNIQUE (member_id, account_id)
);

CREATE TABLE IF NOT EXISTS d105.saving_plans
(
    plan_id bigserial NOT NULL,
	plan_title character varying(50) NOT NULL,
	account_no character varying(50) COLLATE pg_catalog."default" NOT NULL,
    group_id bigint NOT NULL,
    target_amount integer NOT NULL,
    target_date date NOT NULL,
    status character varying(30) COLLATE pg_catalog."default" NOT NULL,
    created_at character varying(50) COLLATE pg_catalog."default" NOT NULL,
    completed_at character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT saving_plans_pkey PRIMARY KEY (plan_id)
);

CREATE TABLE IF NOT EXISTS d105.transactions
(
    transaction_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    transaction_unique_no character varying(50) COLLATE pg_catalog."default" NOT NULL,
    transaction_date date NOT NULL,
    transaction_time time(0) with time zone NOT NULL,
    transaction_type character varying(10) COLLATE pg_catalog."default" NOT NULL,
    amount integer NOT NULL DEFAULT 0,
    is_excluded boolean NOT NULL DEFAULT false,
    CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS d105.user_accounts
(
    account_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    account_no character varying(50) COLLATE pg_catalog."default" NOT NULL,
    bank_code character varying(10) COLLATE pg_catalog."default" NOT NULL,
    bank_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    account_expiry_date timestamp with time zone NOT NULL,
    loaded_at timestamp with time zone NOT NULL,
	last_transaction_sync timestamp with time zone,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT user_accounts_pkey PRIMARY KEY (account_id),
    CONSTRAINT user_accounts_account_no_key UNIQUE (account_no)
);

CREATE TABLE IF NOT EXISTS d105.user_cards
(
    card_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    card_no character varying(20) COLLATE pg_catalog."default" NOT NULL,
    card_company character varying(50) COLLATE pg_catalog."default" NOT NULL,
    card_expiry_date timestamp with time zone NOT NULL,
    withdrawal_account_no character varying(50) COLLATE pg_catalog."default" NOT NULL,
    loaded_at timestamp with time zone NOT NULL,
	last_transaction_sync timestamp with time zone,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT user_cards_pkey PRIMARY KEY (card_id),
    CONSTRAINT user_cards_card_no_key UNIQUE (card_no)
);

CREATE TABLE IF NOT EXISTS d105.users
(
    user_id bigserial NOT NULL,
    email character varying(30) COLLATE pg_catalog."default" NOT NULL,
    password character varying(60) COLLATE pg_catalog."default" NOT NULL,
    simple_password character varying(200) COLLATE pg_catalog."default" NOT NULL,
    username character varying(200) COLLATE pg_catalog."default" NOT NULL,
    user_key character varying(400) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(100) COLLATE pg_catalog."default" NOT NULL,
    birth_date character varying(100) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(50) COLLATE pg_catalog."default" NOT NULL,
    planer_push_enabled boolean NOT NULL DEFAULT true,
	reporter_push_enabled boolean NOT NULL DEFAULT true,
	transaction_push_enabled boolean NOT NULL DEFAULT true,
    created_at character varying(40) COLLATE pg_catalog."default" NOT NULL,
    updated_at character varying(40) COLLATE pg_catalog."default" NOT NULL,
    deleted_at character varying(40) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_phone_number_key UNIQUE (phone_number),
    CONSTRAINT users_user_key_key UNIQUE (user_key)
);

CREATE TABLE IF NOT EXISTS d105.fcm_token
(
    token_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    group_id bigint,
    fcm_token text NOT NULL,
    device_id character varying(100) NOT NULL,
    device_type character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    CONSTRAINT fcm_token_pkey PRIMARY KEY (token_id),
    CONSTRAINT fcm_token_fcm_token_key UNIQUE (fcm_token)
);

-- AI Reports Table
CREATE TABLE IF NOT EXISTS d105.ai_reports (
    ai_report_id bigserial NOT NULL,
    group_id bigint NOT NULL,
    year_month character varying(7) NOT NULL,
    report_content text NOT NULL,
    generated_at timestamp with time zone NOT NULL DEFAULT now(),
    expires_at timestamp with time zone,
    CONSTRAINT ai_reports_pkey PRIMARY KEY (ai_report_id)
);

-- ==============================================
-- D105 SCHEMA - Foreign Key Constraints
-- ==============================================

ALTER TABLE IF EXISTS d105.account_transactions
    ADD CONSTRAINT account_transactions_account_id_fkey FOREIGN KEY (account_id)
    REFERENCES d105.user_accounts (account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.account_transactions
    ADD CONSTRAINT account_transactions_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES d105.categories (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.account_transactions
    ADD CONSTRAINT account_transactions_transaction_id_fkey FOREIGN KEY (transaction_id)
    REFERENCES d105.transactions (transaction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.card_transactions
    ADD CONSTRAINT card_transactions_card_id_fkey FOREIGN KEY (card_id)
    REFERENCES d105.user_cards (card_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.card_transactions
    ADD CONSTRAINT card_transactions_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES d105.categories (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.card_transactions
    ADD CONSTRAINT card_transactions_transaction_id_fkey FOREIGN KEY (transaction_id)
    REFERENCES d105.transactions (transaction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.group_members
    ADD CONSTRAINT group_members_group_id_fkey FOREIGN KEY (group_id)
    REFERENCES d105.groups (group_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.group_members
    ADD CONSTRAINT group_members_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES d105.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.group_tracking_cards
    ADD CONSTRAINT group_tracking_cards_card_id_fkey FOREIGN KEY (card_id)
    REFERENCES d105.user_cards (card_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.group_tracking_cards
    ADD CONSTRAINT group_tracking_cards_member_id_fkey FOREIGN KEY (member_id)
    REFERENCES d105.group_members (member_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.groups
    ADD CONSTRAINT groups_owner_id_fkey FOREIGN KEY (owner_id)
    REFERENCES d105.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.member_tracking_accounts
    ADD CONSTRAINT member_tracking_accounts_account_id_fkey FOREIGN KEY (account_id)
    REFERENCES d105.user_accounts (account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.member_tracking_accounts
    ADD CONSTRAINT member_tracking_accounts_member_id_fkey FOREIGN KEY (member_id)
    REFERENCES d105.group_members (member_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.saving_plans
    ADD CONSTRAINT saving_plans_group_id_fkey FOREIGN KEY (group_id)
    REFERENCES d105.groups (group_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.transactions
    ADD CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES d105.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.user_accounts
    ADD CONSTRAINT user_accounts_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES d105.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.user_cards
    ADD CONSTRAINT user_cards_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES d105.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.fcm_token
    ADD CONSTRAINT fcm_token_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES d105.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS d105.ai_reports
   ADD CONSTRAINT ai_reports_group_id_fkey FOREIGN KEY (group_id)
   REFERENCES d105.groups (group_id) MATCH SIMPLE
   ON UPDATE NO ACTION
   ON DELETE NO ACTION
   NOT VALID;

-- ==============================================
-- D105 SCHEMA - Performance Indexes
-- ==============================================

-- transactions 테이블 인덱스 (가장 중요)
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON d105.transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_date ON d105.transactions(transaction_date);
CREATE INDEX IF NOT EXISTS idx_transactions_user_date ON d105.transactions(user_id, transaction_date);
CREATE INDEX IF NOT EXISTS idx_transactions_type ON d105.transactions(transaction_type);
CREATE INDEX IF NOT EXISTS idx_transactions_excluded ON d105.transactions(is_excluded);

-- card_transactions 테이블 인덱스
CREATE INDEX IF NOT EXISTS idx_card_transactions_card_id ON d105.card_transactions(card_id);
CREATE INDEX IF NOT EXISTS idx_card_transactions_category ON d105.card_transactions(category_id);
CREATE INDEX IF NOT EXISTS idx_card_transactions_merchant ON d105.card_transactions(merchant_name);

-- account_transactions 테이블 인덱스
CREATE INDEX IF NOT EXISTS idx_account_transactions_account_id ON d105.account_transactions(account_id);
CREATE INDEX IF NOT EXISTS idx_account_transactions_category ON d105.account_transactions(category_id);
CREATE INDEX IF NOT EXISTS idx_account_transactions_type ON d105.account_transactions(account_transaction_type);

-- users 테이블 인덱스
CREATE INDEX IF NOT EXISTS idx_users_phone ON d105.users(phone_number);
CREATE INDEX IF NOT EXISTS idx_users_email ON d105.users(email);

-- groups 테이블 인덱스
CREATE INDEX IF NOT EXISTS idx_groups_owner_id ON d105.groups(owner_id);
CREATE INDEX IF NOT EXISTS idx_groups_invitation_code ON d105.groups(invitation_code);
CREATE INDEX IF NOT EXISTS idx_groups_created_at ON d105.groups(created_at);

-- group_members 테이블 인덱스
CREATE INDEX IF NOT EXISTS idx_group_members_group_id ON d105.group_members(group_id);
CREATE INDEX IF NOT EXISTS idx_group_members_user_id ON d105.group_members(user_id);
CREATE INDEX IF NOT EXISTS idx_group_members_status ON d105.group_members(member_status);
CREATE INDEX IF NOT EXISTS idx_group_members_group_user ON d105.group_members(group_id, user_id);

-- user_accounts 테이블 인덱스
CREATE INDEX IF NOT EXISTS idx_user_accounts_user_id ON d105.user_accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_user_accounts_active ON d105.user_accounts(is_active);
CREATE INDEX IF NOT EXISTS idx_user_accounts_bank_code ON d105.user_accounts(bank_code);
CREATE INDEX IF NOT EXISTS idx_user_accounts_last_sync ON d105.user_accounts(last_transaction_sync);

-- user_cards 테이블 인덱스
CREATE INDEX IF NOT EXISTS idx_user_cards_user_id ON d105.user_cards(user_id);
CREATE INDEX IF NOT EXISTS idx_user_cards_active ON d105.user_cards(is_active);
CREATE INDEX IF NOT EXISTS idx_user_cards_company ON d105.user_cards(card_company);
CREATE INDEX IF NOT EXISTS idx_user_cards_last_sync ON d105.user_cards(last_transaction_sync);

-- tracking 테이블 인덱스
CREATE INDEX IF NOT EXISTS idx_member_tracking_accounts_member ON d105.member_tracking_accounts(member_id);
CREATE INDEX IF NOT EXISTS idx_member_tracking_accounts_account ON d105.member_tracking_accounts(account_id);
CREATE INDEX IF NOT EXISTS idx_group_tracking_cards_member ON d105.group_tracking_cards(member_id);
CREATE INDEX IF NOT EXISTS idx_group_tracking_cards_card ON d105.group_tracking_cards(card_id);

-- saving_plans 테이블 인덱스
CREATE INDEX IF NOT EXISTS idx_saving_plans_group_id ON d105.saving_plans(group_id);
CREATE INDEX IF NOT EXISTS idx_saving_plans_status ON d105.saving_plans(status);
CREATE INDEX IF NOT EXISTS idx_saving_plans_target_date ON d105.saving_plans(target_date);

-- fcm_token 테이블 인덱스
CREATE INDEX IF NOT EXISTS idx_fcm_token_user_id ON d105.fcm_token(user_id);
CREATE INDEX IF NOT EXISTS idx_fcm_token_group_id ON d105.fcm_token(group_id);
CREATE INDEX IF NOT EXISTS idx_fcm_token_device_id ON d105.fcm_token(device_id);

-- ai_reports 인덱스
CREATE INDEX IF NOT EXISTS idx_ai_reports_group_id ON d105.ai_reports(group_id);
CREATE INDEX IF NOT EXISTS idx_ai_reports_group_month ON d105.ai_reports(group_id, year_month);
CREATE INDEX IF NOT EXISTS idx_ai_reports_expires_at ON d105.ai_reports(expires_at);

-- ==============================================
-- D105_READ SCHEMA - Denormalized Tables
-- ==============================================

-- 1. user_monthly_expense_stats (개인 월별 지출 카테고리 통계)
CREATE TABLE IF NOT EXISTS d105_read.user_monthly_expense_stats (
    user_id bigint NOT NULL,
    year_month character varying(7) NOT NULL,
    category_id smallint NOT NULL,
    category_name character varying(100) NOT NULL,
    expense_amount bigint NOT NULL DEFAULT 0,
    transaction_count integer NOT NULL DEFAULT 0,
    expense_percentage decimal(5,2) NOT NULL DEFAULT 0.00,
    transaction_ids jsonb,
    last_updated timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_monthly_expense_stats_pkey PRIMARY KEY (user_id, year_month, category_id)
) PARTITION BY RANGE (year_month);

-- 2. group_monthly_expense_stats (그룹 월별 지출 카테고리 통계)
CREATE TABLE IF NOT EXISTS d105_read.group_monthly_expense_stats (
    group_id bigint NOT NULL,
    year_month character varying(7) NOT NULL,
    category_id smallint NOT NULL,
    category_name character varying(100) NOT NULL,
    total_expense bigint NOT NULL DEFAULT 0,
    transaction_count integer NOT NULL DEFAULT 0,
    member_count integer NOT NULL DEFAULT 0,
    expense_percentage decimal(5,2) NOT NULL DEFAULT 0.00,
    last_updated timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT group_monthly_expense_stats_pkey PRIMARY KEY (group_id, year_month, category_id)
) PARTITION BY RANGE (year_month);

-- 3. group_member_monthly_expense_stats (그룹 멤버별 월별 지출 카테고리 통계)
CREATE TABLE IF NOT EXISTS d105_read.group_member_monthly_expense_stats (
    group_id bigint NOT NULL,
    user_id bigint NOT NULL,
    year_month character varying(7) NOT NULL,
    category_id smallint NOT NULL,
    category_name character varying(100) NOT NULL,
    expense_amount bigint NOT NULL DEFAULT 0,
    transaction_count integer NOT NULL DEFAULT 0,
    expense_percentage decimal(5,2) NOT NULL DEFAULT 0.00,
    last_updated timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT group_member_monthly_expense_stats_pkey PRIMARY KEY (group_id, user_id, year_month, category_id)
) PARTITION BY RANGE (year_month);

-- 4. user_monthly_totals (개인 월별 총합)
CREATE TABLE IF NOT EXISTS d105_read.user_monthly_totals (
    user_id bigint NOT NULL,
    year_month character varying(7) NOT NULL,
    total_amount bigint NOT NULL DEFAULT 0,
    transaction_count integer NOT NULL DEFAULT 0,
    uncategorized_amount bigint NOT NULL DEFAULT 0,
    last_updated timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_monthly_totals_pkey PRIMARY KEY (user_id, year_month)
) PARTITION BY RANGE (year_month);

-- 5. group_monthly_totals (그룹 월별 총합)
CREATE TABLE IF NOT EXISTS d105_read.group_monthly_totals (
    group_id bigint NOT NULL,
    year_month character varying(7) NOT NULL,
    total_amount bigint NOT NULL DEFAULT 0,
    active_member_count integer NOT NULL DEFAULT 0,
    avg_amount_per_member bigint NOT NULL DEFAULT 0,
    last_updated timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT group_monthly_totals_pkey PRIMARY KEY (group_id, year_month)
) PARTITION BY RANGE (year_month);

-- 6. group_daily_summary (그룹 일별 요약 - 캘린더용)
CREATE TABLE IF NOT EXISTS d105_read.group_daily_summary (
    group_id bigint NOT NULL,
    summary_date date NOT NULL,
    year_month character varying(7) NOT NULL, -- 추가된 컬럼
    total_amount bigint NOT NULL DEFAULT 0,
    transaction_count integer NOT NULL DEFAULT 0,
    last_updated timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT group_daily_summary_pkey PRIMARY KEY (group_id, summary_date, year_month)
) PARTITION BY RANGE (year_month);

-- 7. user_daily_summary (개인 일별 요약 - 개인 캘린더용)
CREATE TABLE d105_read.user_daily_summary (
    user_id bigint NOT NULL,
    year_month character varying(7) NOT NULL,  -- 추가
    summary_date date NOT NULL,
    total_amount bigint NOT NULL DEFAULT 0,
    transaction_count integer NOT NULL DEFAULT 0,
    transaction_ids jsonb,
    last_updated timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_daily_summary_pkey PRIMARY KEY (user_id, year_month, summary_date)  -- 복합키 변경
) PARTITION BY RANGE (year_month);  -- 파티션키 변경

-- ==============================================
-- D105_READ SCHEMA - Performance Indexes
-- ==============================================

-- user_monthly_expense_stats 인덱스
CREATE INDEX IF NOT EXISTS idx_user_monthly_expense_user_id ON d105_read.user_monthly_expense_stats(user_id);
CREATE INDEX IF NOT EXISTS idx_user_monthly_expense_category ON d105_read.user_monthly_expense_stats(category_id);
CREATE INDEX IF NOT EXISTS idx_user_monthly_expense_user_month ON d105_read.user_monthly_expense_stats(user_id, year_month);
CREATE INDEX IF NOT EXISTS idx_user_monthly_expense_transaction_ids ON d105_read.user_monthly_expense_stats USING GIN(transaction_ids);

-- group_monthly_expense_stats 인덱스
CREATE INDEX IF NOT EXISTS idx_group_monthly_expense_group_id ON d105_read.group_monthly_expense_stats(group_id);
CREATE INDEX IF NOT EXISTS idx_group_monthly_expense_category ON d105_read.group_monthly_expense_stats(category_id);
CREATE INDEX IF NOT EXISTS idx_group_monthly_expense_group_month ON d105_read.group_monthly_expense_stats(group_id, year_month);

-- group_member_monthly_expense_stats 인덱스
CREATE INDEX IF NOT EXISTS idx_group_member_expense_group_id ON d105_read.group_member_monthly_expense_stats(group_id);
CREATE INDEX IF NOT EXISTS idx_group_member_expense_user_id ON d105_read.group_member_monthly_expense_stats(user_id);
CREATE INDEX IF NOT EXISTS idx_group_member_expense_category ON d105_read.group_member_monthly_expense_stats(category_id);
CREATE INDEX IF NOT EXISTS idx_group_member_expense_group_user ON d105_read.group_member_monthly_expense_stats(group_id, user_id);

-- user_monthly_totals 인덱스
CREATE INDEX IF NOT EXISTS idx_user_monthly_totals_user_id ON d105_read.user_monthly_totals(user_id);
CREATE INDEX IF NOT EXISTS idx_user_monthly_totals_year_month ON d105_read.user_monthly_totals(year_month);

-- group_monthly_totals 인덱스
CREATE INDEX IF NOT EXISTS idx_group_monthly_totals_group_id ON d105_read.group_monthly_totals(group_id);
CREATE INDEX IF NOT EXISTS idx_group_monthly_totals_year_month ON d105_read.group_monthly_totals(year_month);

-- group_daily_summary 인덱스
CREATE INDEX IF NOT EXISTS idx_group_daily_summary_group_id 
    ON d105_read.group_daily_summary(group_id);

CREATE INDEX IF NOT EXISTS idx_group_daily_summary_date 
    ON d105_read.group_daily_summary(summary_date);

CREATE INDEX IF NOT EXISTS idx_group_daily_summary_group_date 
    ON d105_read.group_daily_summary(group_id, summary_date);

-- year_month는 파티션 키이므로 별도 인덱스 불필요
-- 각 파티션 내에서 group_id + summary_date 조합으로 최적화

-- user_daily_summary 인덱스
-- 기본 복합 인덱스
CREATE INDEX idx_user_daily_summary_user_month ON d105_read.user_daily_summary(user_id, year_month);

-- 날짜 조회용
CREATE INDEX idx_user_daily_summary_user_date ON d105_read.user_daily_summary(user_id, summary_date);

-- 특정 월 내 날짜 범위 조회용
CREATE INDEX idx_user_daily_summary_month_date ON d105_read.user_daily_summary(year_month, summary_date);

END;

ALTER TABLE d105.user_cards 
ADD COLUMN cvc_encrypted character varying(255) COLLATE pg_catalog."default";



